language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build ./deployment/docker -t nginx-uda -f deployment/docker/Dockerfile
  - docker build ./api-feed -t udagram-api-feed -f api-feed/Dockerfile
  - docker build ./api-users -t udagram-api-users -f api-users/Dockerfile
  - docker build ./udagram-frontend -t udagram-frontend -f udagram-frontend/Dockerfile
  - docker tag nginx-uda bibleit/nginx-uda:latest
  - docker tag udagram-api-feed bibleit/udagram-api-feed:latest
  - docker tag udagram-api-users bibleit/udagram-api-users:latest
  - docker tag udagram-frontend bibleit/udagram-frontend:latest


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push bibleit/nginx-uda
  - docker push bibleit/udagram-api-feed
  - docker push bibleit/udagram-api-users
  - docker push bibleit/udagram-frontend