language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build ./deployment/docker -t nginx-uda -f deployment/docker/Dockerfile
  - docker build ./api-feed -t udagram-api-feed -f api-feed/Dockerfile --build-arg POSTGRES_USERNAME=$POSTGRES_USERNAME --build-arg POSTGRES_PASSWORD=$POSTGRES_PASSWORD --build-arg POSTGRES_HOST=$POSTGRES_HOST --build-arg POSTGRES_DB=$POSTGRES_DB --build-arg AWS_BUCKET=$AWS_BUCKET --build-arg AWS_REGION=$AWS_REGION --build-arg AWS_PROFILE=$AWS_PROFILE --build-arg JWT_SECRET=$JWT_SECRET --build-arg URL=$URL --build-arg S3_ACCESS_ID=$S3_ACCESS_ID --build-arg S3_ACCESS_KEY=$S3_ACCESS_KEY
  - docker build ./api-users -t udagram-api-users -f api-users/Dockerfile --build-arg POSTGRES_USERNAME=$POSTGRES_USERNAME --build-arg POSTGRES_PASSWORD=$POSTGRES_PASSWORD --build-arg POSTGRES_HOST=$POSTGRES_HOST --build-arg POSTGRES_DB=$POSTGRES_DB --build-arg AWS_BUCKET=$AWS_BUCKET --build-arg AWS_REGION=$AWS_REGION --build-arg AWS_PROFILE=$AWS_PROFILE --build-arg JWT_SECRET=$JWT_SECRET --build-arg URL=$URL 
  - docker build ./udagram-frontend -t udagram-frontend -f udagram-frontend/Dockerfile --build-arg POSTGRES_USERNAME=$POSTGRES_USERNAME --build-arg POSTGRES_PASSWORD=$POSTGRES_PASSWORD --build-arg POSTGRES_HOST=$POSTGRES_HOST --build-arg POSTGRES_DB=$POSTGRES_DB --build-arg AWS_BUCKET=$AWS_BUCKET --build-arg AWS_REGION=$AWS_REGION --build-arg AWS_PROFILE=$AWS_PROFILE --build-arg JWT_SECRET=$JWT_SECRET --build-arg URL=$URL 
  - docker tag nginx-uda bibleit/nginx-uda:latest
  - docker tag udagram-api-feed bibleit/udagram-api-feed:latest
  - docker tag udagram-api-users bibleit/udagram-api-users:latest
  - docker tag udagram-frontend bibleit/udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push bibleit/nginx-uda
  - docker push bibleit/udagram-api-feed
  - docker push bibleit/udagram-api-users
  - docker push bibleit/udagram-frontend