services:
  udagram-api-feed:
    image: bibleit/udagram-frontend:latest
    build:
      context: api-feed/
      dockerfile: Dockerfile

  udagram-api-users:
    image: bibleit/udagram-api-users:latest
    build:
      context: api-users/
      dockerfile: Dockerfile

  udagram-frontend:
    image: bibleit/udagram-api-feed:latest
    build: 
      context: udagram-frontend/
      dockerfile: Dockerfile
    depends_on:
      - udagram-api-feed
      - udagram-api-users
      
network:
  fullstack-application-network