apiVersion: apps/v1
# you need this specified as a deployment. 
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: martinezi/simple-node
        ports:
        - containerPort: 8080
      #this is so an api can reach to check if the application is still healthy.
      # livenessProbe:
      #   httpGet:
      #     path: /health
      #     port: 8080
      #   initialDelayedSeconds: 3
      #   periodSeconds: 3