apiVersion: v1
kind: Service
metadata:
  name: frontend-serv
  labels:
    app: frontend-serv
spec:
  ports:
  - name: "8100"
    port: 80
    targetPort: 80
  selector:
    app: frontend-serv