apiVersion: apps/v1
# you need this specified as a deployment. 
kind: Deployment
metadata:
  name: frontend-serv
  labels:
    app: frontend-serv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-serv
  template:
    metadata:
      labels:
        app: frontend-serv
    spec:
      containers:
      - name: frontend-serv
        image: bibleit/udagram-frontend:no_env
        env:
        - name: POSTGRES_USERNAME
          -valueFrom:
            configMapKeyRef:
              name: env-config
              key: postgres
        - name: POSTGRES_PASSWORD
          -valueFrom:
            configMapKeyRef:
              name: env-config
              key: 2Qepxniw
        - name: POSTGRES_HOST
          -valueFrom:
            configMapKeyRef:
              name: env-config
              key: postgres.c50pfikkerps.us-west-1.rds.amazonaws.com
        - name: POSTGRES_DB
          -valueFrom:
            configMapKeyRef:
              name: env-config
              key: postgres
        - name: AWS_BUCKET
          -valueFrom:
            configMapKeyRef:
              name: env-config
              key: udacity-project-493128253161
        - name: AWS_REGION
          -valueFrom:
            configMapKeyRef:
              name: env-config
              key: us-west-2
        - name: AWS_PROFILE
          -valueFrom:
            configMapKeyRef:
              name: env-config
              key: default
        - name: JWT_SECRET
          -valueFrom:
            configMapKeyRef:
              name: env-config
              key: dfkjasdlkfjalsdkfj
        - name: URL
          -valueFrom:
            configMapKeyRef:
              name: env-config
              key: http://localhost:8100
        ports:
        - containerPort: 80